<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Image1.png" />
    <None Remove="Screenshot 2026-05-27 151955.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\greeting.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Image1.png" />
    <Resource Include="Screenshot 2026-05-27 151955.png" />
  </ItemGroup>

</Project>
